version: '2'
services:
  web:
    container_name: WebServer
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/src

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
